### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by Fu-Zhou-2019** [RL-VIG/LibFewShot#1]
Nice work. Could you please provide the relevant Download links to datasets？

**Comment by WenbinLee** [comment]
Thanks. 
We will make the links of datasets ready as soon as possible.

**Comment by wZuck** [comment]
> Nice work. Could you please provide the relevant Download links to datasets？

@Fu-Zhou-2019  Hi there, we have updated our README with the download links of CUB, Standford Cars/Dogs and *mini*ImageNet  in Google Drive and BaiduPan. The link of *tiered*ImageNet will be updated ASAP.
