### ISSUE TITLE
数据集划分规范问题

### ISSUE THREAD

**Issue by Austin98** [RL-VIG/LibFewShot#100]
有没有统一的数据集格式规范，对于相同的数据集，不同的研究者有不同的划分方式，很难放在一起进行对比呀
希望作者可以提供一个关于数据集设置规范的文档
对于共20个类的数据集怎么划分train text val比较合理呢？
另外对于图片过多的情况，为什么会报错too many values to unpack(expected 2)，无奈只能减少图片，什么原因呢？

**Comment by Austin98** [comment]
比如有的数据集只有10个类，有的只有20个类，应该如何划分呢？

**Comment by VincenDen** [comment]
例如mini-imagenet，tiered-imagenet，CUB等fewshot常用数据集，都是有统一的划分规范的，如果是想使用自己的数据集则需要根据自身需求划分
