### ISSUE TITLE
报错：ModuleNotFoundError: No module named 'core.model.meta.matchingnet' 

### ISSUE THREAD

**Issue by wangjiawen-123** [RL-VIG/LibFewShot#119]
请问为什么报错这个呀？改了yaml，应该也不是数据集的问题。
<img width="455" alt="1" src="https://github.com/user-attachments/assets/7eec5aaf-ca08-4478-932e-9e9de5428702">

**Comment by OnurAltayTopaloglu** [comment]
in LibFewShot\core\model\meta\__init__.py 
change the line:
from .matchingnet import DMatchingNet 
to 
from .matchingnet_ifsl import DMatchingNet
