### ISSUE TITLE
关于代码中REnet模型类型归属问题

### ISSUE THREAD

**Issue by byraid218** [RL-VIG/LibFewShot#121]
REnet在论文里和github的README中被归类为了metric类型，原REnet论文似乎也是度量学习，在测试的时候不会进行train或者finetune，但是在libfewshot的代码里面却被归为ModelType.FINETUNING类，并且model定义也被存放在了finetune的文件夹中，请问这个有什么说法的吗，因为我在寻找一种方法，不在测试集进行训练和finetune。

**Comment by VincenDen** [comment]
论文中应该是pretrain和fintune两个阶段合并为一个阶段，所以放在finetune和metric应该都是可以的
