### ISSUE TITLE
Issue about training the supported methods

### ISSUE THREAD

**Issue by viviGeng** [RL-VIG/LibFewShot#15]
Hi. I have installed LibFewShot successfully, and got correct output by running `test_install.yaml`. However, the script gave the following error message when I tried to run other supported methods listed in `./config`. 
<img width="1306" alt="截屏2021-10-25 下午4 44 45" src="https://user-images.githubusercontent.com/35882731/138666177-622f8487-08af-429b-b4dd-5641b33df5be.png">
Could you give some suggestions about how to solve such problem?

**Comment by wZuck** [comment]
Hi, we think it may be caused by uncertain behaviors of the OS or file system, we will never create the symlink file after 
 commit b050c06eb982defe57be7381e2877571ff561987, you can pull the newest codes to avoid this error.

Feel free to reopen this issue if you meet this error again.
