### ISSUE TITLE
关于LEO的复现

### ISSUE THREAD

**Issue by Skyraker2016** [RL-VIG/LibFewShot#16]
你好，首先感谢你们对多种小样本方法的复现及开源。

在运行leo.yaml配置时我注意到它需要pretrain的模型：`pretrain_path: ./results/checkpoint.pth`。请问这个模型是用什么方法预训练的呢？

另外在运行其它方法时，根据给出的配置我跑出了和论文差距不小的结果，我注意到您在 #9 中提到过将放出具体配置，请问目前有哪些方法已经整理好了配置，能否更新一下，十分感谢！

**Comment by wZuck** [comment]
你好，我们正在逐步地更新[训练配置文件](https://github.com/RL-VIG/LibFewShot/tree/main/config/reproduce)和[模型文件](https://drive.google.com/drive/folders/16DWKKqjzALoq4qb8LZQ6oELD9SGlYWe_?usp=sharing)，其中也包含了我们在LEO中使用的RFS预训练模型，你可以参考以上链接或者最新的进展。
