### ISSUE TITLE
Config files to reproduce the paper's results

### ISSUE THREAD

**Issue by MosyMosy** [RL-VIG/LibFewShot#19]
Hi, Thank you for your great job. Currently, I am reproducing the exact evaluations you have reported on the paper (especially Table 2). For sure it is easily reproducible from your complete tutorial, but I want to make sure I am going in exactly the right setting. So I will appreciate it if you can share the appropriate configs related to each table, If you already have them.

**Comment by wZuck** [comment]
Hi, sorry for replying so late. We have just added the `config/reproduce` directory for providing producible configs and the corresponding checkpoints. You can follow the instructions at [Train/test existing methods in LibFewShot](https://libfewshot-en.readthedocs.io/en/latest/tutorials/t1-train_and_test_exist_methods.html#test) to test our checkpoints.

We will release more checkpoints as soon as possible.

**Comment by MosyMosy** [comment]
Thanks, @wZuck. Perfect job.

**Comment by MosyMosy** [comment]
I will appreciate it if you share other method backbones too.
