### ISSUE TITLE
code

### ISSUE THREAD

**Issue by LLLLL13579** [RL-VIG/LibFewShot#2]
Hello,  there are several methods that run code with errors, such as relation, maml, mtl, leo, etc. And several methods to change the embedding backbone also have errors.

**Comment by yangcedrus** [comment]
> there are several methods that run code with errors, such as relation, maml, mtl, leo, etc.

Thanks for pointing this out, we have fixed the issue.

> And several methods to change the embedding backbone also have errors.

Please notice that some methods need to change the parameter of `feat_dim` or some other parameters  when using different backbones.
