### ISSUE TITLE
pre-trained weights

### ISSUE THREAD

**Issue by eladmeir** [RL-VIG/LibFewShot#20]
Hey 
I wanted to test a few of them "general pre trained" models in order to fine tune using my poor single GPU
Due to limits of hardware and time, I cannot reproduce the pre-trained results of the first stage, thus I cannot further analyze the performance of fine tuning.

Are you planning on releasing some of your checkpoint files?

Anyhow - great work, I love it and already use it a lot in my research. Keep on the good work

**Comment by wZuck** [comment]
You can download the pre-trained weight from [here](https://drive.google.com/drive/folders/16DWKKqjzALoq4qb8LZQ6oELD9SGlYWe_?usp=sharing). In `model_zoo/RFS`, there is a folder named `RFS-miniImageNet`, you can download and place it in the results folder of the LibFewShot directory. Make sure you have set the `augment_times` to `5` before running the test.

We will release more checkpoints with their configs in this [link](https://drive.google.com/drive/folders/16DWKKqjzALoq4qb8LZQ6oELD9SGlYWe_?usp=sharing). Welcome to follow our follow-up progress.

**Comment by eladmeir** [comment]
Thanks, I'll sure follow
