### ISSUE TITLE
For Baseline, Train in the trainset goes up to 300 while supposed to be 2000

### ISSUE THREAD

**Issue by MosyMosy** [RL-VIG/LibFewShot#21]
Hi, I am evaluating the Baseline and ProtoNet with exactly the same setting while the `train_episode: 2000` and `test_episode: 2000`. In ProtoNet the Train in the trainset goes up to 2000 in each epoch, but this up to 300 for the Baseline. 
Is there any special setting I have accidentally set to 300? 
Or it is as expected for the Baseline?

**Comment by wZuck** [comment]
Methods under the [`finetuning`](https://github.com/RL-VIG/LibFewShot/tree/main/core/model/finetuning) directory are different from other few-shot methods. In the training stage, they use generic batches. 

Briefly, `train_episode` is not used in `finetuning - set_forward_loss()`, you need to specify the [`batch_size`](https://github.com/RL-VIG/LibFewShot/blob/594efc980bc8b58e132ce3796e150732ccec6fed/config/headers/model.yaml#L21)  parameter, default we set it to `128`, *mini*ImageNet contains 38400 training images, so you will get `38400/128=300` batches in the training-stage.

**Comment by MosyMosy** [comment]
Thank you @wZuck.
