### ISSUE TITLE
Five time evaluation in Evaluation protocole

### ISSUE THREAD

**Issue by MosyMosy** [RL-VIG/LibFewShot#22]
Hi, on section 3. Evaluation Settings and LibFewSh > Evaluation Protocols, it is stated that "we control the evaluation setting for all methods, evaluate them on 2000 sampled tasks and repeat this process five times, i.e., a total of 10000 tasks". 
It seems you have used different seed values for each of these evaluations, I will appreciate it if you can share that five seeds list (the default is 0 now).
Or If all of them are evaluated with the same seed, I am wonder what will be the difference between five-time 2000 episodes and one-time 10000 episodes?

**Comment by wZuck** [comment]
You can set any seed. For example, when set [`test_epochs`](https://github.com/RL-VIG/LibFewShot/blob/594efc980bc8b58e132ce3796e150732ccec6fed/config/headers/model.yaml#L2) to `2`, the test episodes in test-epoch-1 and test-epoch-2 are different, so you don't need to worry about that question. Actually, in the training stage, the episodes in train-epoch-1 and train-epoch-2 are also different.
