### ISSUE TITLE
Accuracy of CAN Method

### ISSUE THREAD

**Issue by viviGeng** [RL-VIG/LibFewShot#24]
Hi, I tried to reproduce the accuracy of CAN method. However, the accuracy turns out to be weird.
So that I print the intermediate steps and the returned value once `line 327` in `can.py` is called.

```
acc = accuracy(cls_scores, query_targets, topk=1)
```
One example of output:
```
batch_size:  1
correct:  tensor([[1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
         1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
         0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0,
         0, 0, 0]], device='cuda:0', dtype=torch.uint8)
correct_k:  tensor([30.], device='cuda:0')
 acc:  3000.0
```
The accuracy is too large. Also, the batch_size is set as `128` in the config file, rather than the output value `1`.

**Comment by wZuck** [comment]
Thank you for reporting this issue. You can modify `line 327` to 
```
acc = accuracy(cls_scores, query_targets.view(-1), topk=1)
```
We will update `can.py` later.

And `CAN` uses episodic-tasks in both the training and testing stage, so `batch_size` is useless in this method, you can set `episode_size` for training/testing/debugging.

If you are using the `main` branch of `LibFewShot`, you will get the `episode_size = episode_size`. If you are using the `add_ddp` branch of `LibFewShot`, you will only get the `episode_size = episode_size / n_gpu`.

**Comment by viviGeng** [comment]
Thank you for your reply.
I have another question about the shape of input data with different parameter setting.
For training `CAN` model using `miniImageNet`,  set `batch_size =  32  episode_size = 1  n_gpu = 1`, then the shape of input data is `[100,3,84,84]`. If we change the setting as `batch_size =  128  episode_size = 1  n_gpu = 1`, then the shape of input data is `[80,3,84,84]`.
It seems the first element of shape array is somehow relevant to `batch_size`. Could you give me some suggestion about how to set those parameters appropriately.

**Comment by wZuck** [comment]
Could you upload your config of 2 different settings? It's better if you can upload the `config.yaml` in the checkpoint's directory.
```
CAN-miniImageNet--ravi-Conv64F-5-1-XXXXXXXXXXXX
├── checkpoints
├── config.yaml        # <- this file
└── log_files
```
You may set `shot/test_shot` to different values accidentally. Beacause `100 = 5way * (5shot+15query)` and `80 = 5way * (1shot+15query)`

**Comment by viviGeng** [comment]
Thank you for the explanation. 
The difference is caused by value of `shot`.
