### ISSUE TITLE
关于ReadMe中提供的百度网盘数据集似乎不能使用在这个框架下

### ISSUE THREAD

**Issue by Littlesharkcug** [RL-VIG/LibFewShot#28]
我下载了百度网盘下面的miniimagenet，解压以后是pickle文件，并不是支持的格式。是不是其他的数据集也都需要自己去找呢。
dataset_folder/
├── images/
│   ├── images_1.jpg
│   ├── ...
│   └── images_n.jpg
├── train.csv *
├── test.csv *
└── val.csv *

**Comment by wZuck** [comment]
感谢你的issue，我们已经上传了了百度网盘的数据集，请重新下载使用。
