### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './config/classifiers/RENet.yaml'

### ISSUE THREAD

**Issue by tangdouer** [RL-VIG/LibFewShot#31]
FileNotFoundError: [Errno 2] No such file or directory: './config/classifiers/RENet.yaml'

**Comment by wZuck** [comment]
Thanks for your issue. The implementation of `RENet` is still under testing, we will update the `RENet` classifier to the `main` branch as soon as possible. At the same time, it will bring a major update of `LibFewShot`.
