### ISSUE TITLE
在headers里面是否缺少一个losses.yaml。

### ISSUE THREAD

**Issue by feifeia-a** [RL-VIG/LibFewShot#32]
作者大大，你好，在headers里面是否缺少一个losses.yaml呢？在准备数据集（以miniImagenet为例）的例子中，你们采用了ProtoNet为例，需要新写一个yaml文件getting_started.yaml，在getting_started.yaml文件中有一个losses.yaml，但在我们下载的headers文件里并没有losses.yaml文件。

**Comment by wZuck** [comment]
谢谢你的反馈，我们遗漏了文档中该部分内容，`losses.yaml`在本份代码中已经移除，你可以在`getting_started.yaml`中删除该行完成测试。
