### ISSUE TITLE
检测结果可视化

### ISSUE THREAD

**Issue by ZZY-666** [RL-VIG/LibFewShot#41]
首先感谢贵团队优秀的工作！但是在test阶段，该lib库好像只能显示平均检测精度和检测时间，并不能对检测结果可视化（无法进行类似目标检测的框出物体）也不能对每类的检测精度进行显示，请问后期贵团队有实现上述功能的计划吗？

**Comment by wZuck** [comment]
感谢你对我们LibFewShot的认同。关于您提出的两点建议我们想进一步了解一下，对于“检测结果可视化”你是指使用基于Class Activation Mapping对每个小样本任务中的对应support和query都生成这样的热区渲染图吗，还是目标检测方法中的Bounding Box？；关于“对每类的检测精度进行显示”这一点，这个功能你是指在一个task内的每个类别的分类精度，还是指整个测试阶段结束后，在测试集上每个类的分类准确率？

**Comment by ZZY-666** [comment]
感谢您的回复，
关于“检测结果可视化”：我主要指的是目标检测方法中的Bounding Box，以及每类物体所属类别及置信度（类似于运行yolov5的detect.py所产生可视化结果）；
关于“对每类的检测精度进行显示”：我指的是整个测试阶段结束后，在测试集上每个类的分类准确率，个人认为这是模型学习能力的有力表征，通过分析不同尺度目标的检测精度在一定程度上也能指明模型的改进方向。
若能实现以上两点，无疑是这个优秀项目的进一步完善，相信对大家的学术研究也大有裨益！
请问有完善的计划吗？再次对这个优秀的项目表示赞赏！

**Comment by wZuck** [comment]
再次谢谢您的肯定！可能需要跟您解释一下，目前LibFewShot暂时只支持图像分类任务，暂时不支持目标检测任务。
关于可视化功能，因为在小样本分类任务中一般不会考虑目标检测中的这些指标，所以我们可能暂时不会加入该功能；
关于对每类的检测精度进行显示，这个功能是可以实现的，但是由于小样本分类任务设置的特性，在全局数据集上考虑整体的分类准确率似乎不太合理，应该更关注在任务层面的分类准确率，当前该研究方向的指标也都是如此设置的，所以这个功能我们暂时不考虑加入。 
再次感谢您的建议！
