### ISSUE TITLE
hyperspectral images

### ISSUE THREAD

**Issue by maxwell1386** [RL-VIG/LibFewShot#43]
Hi
Thanks for sharing this code.
Is it possible to use this library with images more than 3 channels for example hyper spectral images with 256 channels?

**Comment by yangcedrus** [comment]
Thanks for your issue.

LibFewShot is mainly designed for 3-channel based RGB images and the design of backbones also follows this. If you need to deal with images more than 3 channels, you can easily modify the backbone accordingly. Thanks.
