### ISSUE TITLE
How to set syncbn in this codebase

### ISSUE THREAD

**Issue by JwFbupt** [RL-VIG/LibFewShot#44]
Hi when i use this codebase for training. I want to use syncbn in DDP mode. How can I achieve that?

**Comment by wZuck** [comment]
Hi, you can switch to the branch `add_ddp` and then checkout to commit deeed4baf4f7f516a71a168cff8121c305b66075 (commits after deeed4baf4f7f516a71a168cff8121c305b66075 are not stable now). When you use multiple GPUs, the SyncBN module will replace the BN automatically, refer to https://github.com/RL-VIG/LibFewShot/blob/deeed4baf4f7f516a71a168cff8121c305b66075/core/trainer.py#L420
If any error occurs, please let us know. Thanks for using `LibFewShot`.
