### ISSUE TITLE
Suggest to support Semi-supervised and Unsupervised FSL method in the future

### ISSUE THREAD

**Issue by zhang1hongliang** [RL-VIG/LibFewShot#46]
Thank you for the most helpful FSL Library which is suitable for supervised FSL, we want this library will support Semi-supervised and Unpervised FSL method. Thanks again for the useful library.

**Comment by wZuck** [comment]
Thanks for your advice. `LibFewShot` mainly aims to support supervised few-shot learning methods, some components are also designed to be suitable with supervised scenario. We may develop more `Libs` for semi-supervised or unsupervised few-shot methods in future works.
