### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'config'

### ISSUE THREAD

**Issue by yy-wy** [RL-VIG/LibFewShot#52]
Traceback (most recent call last):
  File "E:/code/mildew/LibFewShot/run_trainer.py", line 31, in <module>
    trainer = Trainer(config)
TypeError: __init__() missing 1 required positional argument: 'config'

**Comment by wZuck** [comment]
Could you paste your `run_trainer.py` and describe your modification on the `LibFewShot` in detail?

**Comment by yy-wy** [comment]
![image](https://user-images.githubusercontent.com/61910311/192931715-28c562be-87f1-430b-be5d-c556a78448c5.png)
根据这个步骤进行更改会有上述错误。
但是如果不做任何更改是没有问题的

**Comment by wZuck** [comment]
你好，近期我们在LibFewShot合并了DDP，做了一些修改，文档还没有及时更新，如果需要使用别的`yaml`文件，只需要修改字符串为你的配置文件路径即可。
