### ISSUE TITLE
自己的单个数据是二维的  及类别  可以使用few shot 分类吗？

### ISSUE THREAD

**Issue by henbucuoshanghai** [RL-VIG/LibFewShot#53]

**Comment by wZuck** [comment]
你是指数据的格式为 `[C,H,W] = [1,H,W]` 吗，如果是这样的话，可以。但是因为代码中都是对3通道图像做处理的，因此需要对dataloader或者backbone稍作修改。

**Comment by henbucuoshanghai** [comment]
感谢回复自己的单个数据 是 1，h,w的维度&nbsp; &nbsp;及类别&nbsp;&nbsp;
我把1维度扩展为三维 ，就可以和代码对齐了？
感谢

**Comment by wZuck** [comment]
是的，你可以在 https://github.com/RL-VIG/LibFewShot/blob/f002bf351f46ff68664906c4903916983abc2f02/core/data/dataset.py#L177-L179 里修改图片载入逻辑，读取灰度图像并转换为三通道图像。https://github.com/RL-VIG/LibFewShot/blob/f002bf351f46ff68664906c4903916983abc2f02/core/data/dataloader.py#L12-L13 这里的`MEAN`和`STD`是在ImageNet上统计得到的参数，如有需要可以自行修改。
