### ISSUE TITLE
Very amazing work. But loses.yaml is missing under config/headers！

### ISSUE THREAD

**Issue by Aquariuaa** [RL-VIG/LibFewShot#61]

**Comment by wZuck** [comment]
Thanks for your attention to `LibFewShot`. For the solution of 'losses.yaml', please redirect to https://github.com/RL-VIG/LibFewShot/issues/26#issuecomment-969868609

**Comment by Aquariuaa** [comment]
Thank you very much! One other question.
(torchLFS) [inspur@localhost LibFewShot-main]$ python run_trainer.py
Traceback (most recent call last):
  File "run_trainer.py", line 6, in <module>
    trainer = Trainer(config)
TypeError: __init__() missing 1 required positional argument: 'config'
Is this not installed successfully?

**Comment by wZuck** [comment]
You may pull the latest version of `LibFewShot` and try again. Notice #52.
