### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: './config/backbones/Conv64FLeakyReLU.yaml'

### ISSUE THREAD

**Issue by Aquariuaa** [RL-VIG/LibFewShot#62]
Thank you very much! The following documents are missing
：
FileNotFoundError: [Errno 2] No such file or directory: './config/backbones/Conv64FLeakyReLU.yaml'

**Comment by wZuck** [comment]
'Conv64FLeakyReLU.yaml' is deprecated. Could you tell me which config you are using?

**Comment by Aquariuaa** [comment]
非常感谢！是否有对classifier中的参数做出说明的文档呢？如
classifier:
  name: RelationNet
  kwargs:
    feat_dim: 64
    feat_height: 3
    feat_width: 3
中的feat_dim、feat_height等等，是否需要与backbones中的网络相对应？
再次感谢！！！

**Comment by wZuck** [comment]
这些参数可以在https://github.com/RL-VIG/LibFewShot/blob/ee25973ac87e5e1b654c7191ad122ea727d0eba1/core/model/metric/relation_net.py#L29 中对应找到，它们和backbone的网络会有一定的对应关系，但如果你需要，可以根据自己的需求修改。默认的参数我们按照原文/原代码进行设置。
