### ISSUE TITLE
请问目前Libfewshot支持几种数据集？谢谢

### ISSUE THREAD

**Issue by neverstoplearn** [RL-VIG/LibFewShot#64]

**Comment by wZuck** [comment]
如README https://github.com/RL-VIG/LibFewShot/blob/4dcc614ff66532eb8174242b3ba5800b8e624dab/README.md?plain=1#L54-L55 所述，`LibFewShot`现在提供了 [Caltech-UCSD Birds-200-2011](https://data.caltech.edu/records/20098), [Standford Cars](https://ai.stanford.edu/~jkrause/cars/car_dataset.html), [Standford Dogs](http://vision.stanford.edu/aditya86/ImageNetDogs/main.html), [miniImageNet](https://arxiv.org/abs/1606.04080v2) 和 [tieredImageNet](https://arxiv.org/abs/1803.00676) 等常用数据集的Google Drive和百度网盘资源。但并不仅限于此，你可以按照 [准备数据集](https://libfewshot-en.readthedocs.io/zh_CN/latest/getting_started.html#miniimagenet) 的说明构建新的数据集。
