### ISSUE TITLE
Questions about codes in can.py

### ISSUE THREAD

**Issue by blurryK** [RL-VIG/LibFewShot#74]
Hi,

An error occurred when running the CAN model with 5way 5shot setting. 
`File "/LibFewShot-main/core/model/metric/can.py", line 381, in set_forward_loss
    episode_size, self.way_num
RuntimeError: shape '[1, 5]' is invalid for input of size 25`
I suppose the code here 

> https://github.com/RL-VIG/LibFewShot/blob/main/core/model/metric/can.py#L381

should be 
`support_targets = support_targets.reshape(
            episode_size, self.way_num * self.shot_num
        ).contiguous()` .
Maybe there are other workarounds available?

**Comment by wZuck** [comment]
Thanks for reporting this error, it may be caused by a previous git-merge, we will fix it ASAP.

**Comment by wZuck** [comment]
Implementations have been fixed, thanks for your issue.
