### ISSUE TITLE
train，val和test类别问题

### ISSUE THREAD

**Issue by dengxunzhi** [RL-VIG/LibFewShot#78]
非常感谢提供这么好的小样本学习库，对于初学者非常友善，我有个小问题想要请教下。代码和论文中使用的几个数据集中，train，val和test的类别都是不相交的（如miniImageNet共100类，其中train有64类，val有16类，test有20类），我的理解train和val是基类（base），test是新类（novel），不知我的理解是否正确，如果正确的话，那么train和val的类别是否可以相同呢？比如miniImageNet中设置train和val都有80（64+16）类。

**Comment by wZuck** [comment]
+ train是base，val和test都是novel。
+ 一般不会这样做，不排除某些方法是用了train+val的组合作为训练集。

**Comment by dengxunzhi** [comment]
比如在实际用小样本做分类时，有1个基类（记作BaseA，公开数据集），我想用这个基类做预训练，然后迁移到新类（记作NovelB，自己手工标注）上进行微调和精度测试，NovelB的类别非常少，比如每类只有25个样本，其中5个做支撑集，25个做查询集。
那么我的train应该是BaseA，test应该是NovelB，val这时候应该设置成什么呢，我理解的val应该是从BaseA中选择一部分用来挑选预训练的最优模型。

**Comment by wZuck** [comment]
如果是面向实际的业务而不是研究，那么你的val可以使用NovelB的一部分。另外，从你的表述来看，我不太能理解用1个基类如何预训练。

**Comment by dengxunzhi** [comment]
不好意思，又打扰您了，我还有点不是很理解。我的目的是面像实际业务，想使用少量标注的新类样本就能够得到一个微调的模型，用于实际分类工作。
如果NovelB只有11类，那么val是使用其中的几类（比如5类）吗，还是使用全部的11类呢？如果使用其中的几类的话，那么只用剩下的类别做微调测试的话，类别不全，不能满足实际11个类别的分类。如果使用全部的11类的话，那么我是不是要多标注一些样本作为val呢？
（不好意思我这里说的1个基类是指一个数据集，里面有好多类，比如16类。用基类做预训练的话，全部类别参与预训练，90%作为train，10%作为val）

**Comment by dengxunzhi** [comment]
还有我看论文和代码中val和test是不相交的类别，val和test都属于novel，为什么不能相交呢（为什么不能都包含相同的类别呢）？

**Comment by wZuck** [comment]
如果是针对实际业务的话，我建议可以先选择一个简单的方法例如ProtoNet，使用本仓库提供的预训练模型，在你的NovelB数据集上进行测试，看精度是否满足要求。

如果需要进行微调的话，我觉得可以尝试：
1. 在BaseA的16个类中，选择<=11个类作为train微调，剩下的用于val集选择模型；或
2. 使用全部BaseA微调，从NovelB的每类数据中选取一部分样本用于测试，这可能需要再额外标注一些数据。

关于数据集划分的问题，可以参考[d2l 4.4.2.1. 验证集](https://zh.d2l.ai/chapter_multilayer-perceptrons/underfit-overfit.html#id6).

**Comment by dengxunzhi** [comment]
非常感谢您的解答
