### ISSUE TITLE
How to use this code into open-set recognition?

### ISSUE THREAD

**Issue by jianandeng023** [RL-VIG/LibFewShot#79]
Recently, I want to introduce few-shot learning into open-set recognition, can you try to inplement this area? Thanks

**Comment by wZuck** [comment]
Thanks for your issue. Currently, LibFewShot mainly focuses on few-shot image classification tasks and we do not have immediate plans to expand into other tasks such as open-set recognition.

However, our framework offers a clear and easily modifiable structure, and we encourage you to make specific adjustments tailored to the open-set recognition task.
