### ISSUE TITLE
使用自己数据集的时候会卡在加载训练数据集这一步

### ISSUE THREAD

**Issue by DeeKer2000** [RL-VIG/LibFewShot#80]
使用miniimagnet可以正常进行训练，我换成了自己数据集之后会卡在加载训练集这一步
![image](https://github.com/RL-VIG/LibFewShot/assets/141380929/0011c34e-15bc-452a-ae45-d49574951c2f)

**Comment by VincenDen** [comment]
您好，从图上来看您自定义数据集只有3个label，似乎不足以满足小样本任务设置
