### ISSUE TITLE
5way-5shot报错

### ISSUE THREAD

**Issue by 2561681244** [RL-VIG/LibFewShot#83]
![image](https://github.com/RL-VIG/LibFewShot/assets/108559729/0aef02fe-5521-4f94-843d-f1aee679a2ea)

为什么5way-1shot可以运行，5way-5shot不能运行？

**Comment by VincenDen** [comment]
请展示更详细的配置文件帮助解决您的疑问

**Comment by xiaoxueshneg** [comment]
同样的问题

**Comment by xiaoxueshneg** [comment]
![image](https://github.com/RL-VIG/LibFewShot/assets/56753873/4afd9b64-3ef6-46d4-8bee-37cc26b53845)

**Comment by lingaoqiming123** [comment]
> ![image](https://user-images.githubusercontent.com/108559729/275235638-0aef02fe-5521-4f94-843d-f1aee679a2ea.png)
> 
> 为什么5way-1shot可以运行，5way-5shot不能运行？

**Comment by lingaoqiming123** [comment]
> ![image](https://user-images.githubusercontent.com/108559729/275235638-0aef02fe-5521-4f94-843d-f1aee679a2ea.png)
> 
> 为什么5way-1shot可以运行，5way-5shot不能运行？

相同的问题，大佬解决了吗

**Comment by VincenDen** [comment]
请大家尽可能使用Reproduce目录下的配置文件

**Comment by lingaoqiming123** [comment]
> 请大家尽可能使用Reproduce目录下的配置文件
用论文提供的数据集没什么问题。用WebCaricature数据集在5way-5shot遇到了问题

**Comment by HumbleOLi** [comment]
> 请大家尽可能使用Reproduce目录下的配置文件

对的有同样的问题，请问如果要5w5s，应该改哪些参数呢，谢谢🙏

**Comment by VincenDen** [comment]
> 文

reproduce目录下分别有5w1s和5w5s的配置文件
