### ISSUE TITLE
使用miniImageNet--ravi数据集，然后ACC值为什么这么低？

### ISSUE THREAD

**Issue by lmqhello** [RL-VIG/LibFewShot#87]
includes:
  - headers/data.yaml
  - headers/device.yaml
  - headers/misc.yaml
  - headers/model.yaml
  - headers/optimizer.yaml
  - backbones/resnet18.yaml
  - classifiers/Proto.yaml

就这个配置，其他都没修改，跑出来这么低？？？

**Comment by lmqhello** [comment]
只有30多

**Comment by gaoyangyang-1** [comment]
试试作者在reproduce中提供的配置

**Comment by VincenDen** [comment]
> 试试作者在reproduce中提供的配置

是的，请尽可能使用reproduce文件

**Comment by William20234** [comment]
我也有这个问题，config的model.yaml里面把shot改成5，实际训练过程中输出的信息还是1

**Comment by VincenDen** [comment]
> 我也有这个问题，config的model.yaml里面把shot改成5，实际训练过程中输出的信息还是1

麻烦使用reproduce目录下的配置文件试试
