### ISSUE TITLE
RENet

### ISSUE THREAD

**Issue by Betty-code12** [RL-VIG/LibFewShot#90]
你好，请问RENet不是属于基于度量的吗，为什么放在了core/model/finetuning下，归于了finetune方法呢？
![1699422608818](https://github.com/RL-VIG/LibFewShot/assets/68535813/b9f2f62f-05a1-4142-8c3b-a2420ba4e091)
![1699422633612](https://github.com/RL-VIG/LibFewShot/assets/68535813/767222aa-4bb7-497d-8ee7-6a96e7e54c94)

**Comment by VincenDen** [comment]
关于小样本方法的分类可以参见我们的论文https://www.computer.org/csdl/journal/tp/5555/01/10239698/1Qck3o85t60
