### ISSUE TITLE
renet.yaml的backbone为ViT时的报错解决

### ISSUE THREAD

**Issue by bababa8910** [RL-VIG/LibFewShot#91]
您好，当我运行run_trainer.py（renet.yaml）的时候，renet.yaml的配置如下：
![image](https://github.com/RL-VIG/LibFewShot/assets/97462638/ab60aafa-6ff3-43ae-9cb1-35fd2cdcd88f)
此时backbone为ViT，ViT.yaml配置如下：
![image](https://github.com/RL-VIG/LibFewShot/assets/97462638/85a9b2ce-d0f0-4c93-943e-c3e13fb4b5b7)
但是出现了以下报错，请问应该如何解决？
![image](https://github.com/RL-VIG/LibFewShot/assets/97462638/6aa13cb7-39fa-403c-b29f-685ff8405cb0)
若能解答，感激不尽！

**Comment by VincenDen** [comment]
Vit和卷积网络架构有所区别，并不是所有算法都支持vit架构
