### ISSUE TITLE
训练日志与run_test的test数据差距过大

### ISSUE THREAD

**Issue by marktiwnzhao** [RL-VIG/LibFewShot#92]
我在使用renet+Conv64进行训练时，训练日志的里的test数据与run_test的结果相差很大，这是为什么呢？
![YCU@EIU263809HCC(9_YLN8](https://github.com/RL-VIG/LibFewShot/assets/91530551/820791ff-72b8-4cf5-b356-0a5b87cb3d23)
![N(9FGN{W11AP3NNSZZ10%59](https://github.com/RL-VIG/LibFewShot/assets/91530551/b42be46a-c107-414a-be38-e62075eb7a37)

**Comment by marktiwnzhao** [comment]
发现准确率好像跟run_test里的episode_size有关，两者一致准确率才最高。同时，我也发现有些方法不一致也能保存与训练近似的准确率，是有什么原因吗。

**Comment by VincenDen** [comment]
建议检查一下run_test的配置文件是否和训练时的测试配置一致
