### ISSUE TITLE
use_logger() got an unexpected keyword argument 'file'

### ISSUE THREAD

**Issue by Feiruuuu** [RL-VIG/LibFewShot#94]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luoguofeng/anaconda3/envs/libfewshot/lib/python3.7/threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "/home/luoguofeng/anaconda3/envs/libfewshot/lib/python3.7/threading.py", line 936, in _bootstrap_inner
    (self.name, _format_exc()), file=_sys.stderr)
TypeError: use_logger() got an unexpected keyword argument 'file'

这是我的config
augment: true
augment_times: 1
augment_times_query: 1
backbone:
  kwargs:
    is_feature: false
    is_flatten: false
    last_pool: false
    leaky_relu: false
    maxpool_last2: true
    negative_slope: 0.2
    use_running_statistics: true
  name: Conv64F
batch_size: 128
classifier:
  kwargs:
    n_k: 3
  name: DN4
data_root: /home/luoguofeng/LibFewShot/CIFAR100
dataloader_num: 1
deterministic: true
device_ids: 0,1,2,3
episode_size: 1
epoch: 1
image_size: 84
includes:
- headers/data.yaml
- headers/device.yaml
- headers/misc.yaml
- headers/model.yaml
- headers/optimizer.yaml
- classifiers/Proto.yaml
- backbones/Conv64F.yaml
- headers/losses.yaml
log_interval: 100
log_level: info
log_name: logs
lr_scheduler:
  kwargs:
    gamma: 0.5
    step_size: 10
  name: StepLR
n_gpu: 1
optimizer:
  kwargs:
    lr: 0.01
  name: Adam
  other:
    dn4_layer: 0.001
    emb_func: 0.01
parallel_part:
- emb_func
port: 33707
pretrain_path: null
query_num: 15
rank: 0
result_root: /home/luoguofeng/LibFewShot/results
resume: false
save_interval: 10
save_part:
- emb_func
- dn4_layer
seed: 2147483647
shot_num: 5
tb_scale: 1.0
test_episode: 100
test_epoch: 1
test_query: 15
test_shot: 5
test_way: 5
train_episode: 100
use_memory: false
val_per_epoch: 1
warmup: 0
way_num: 5
workers: 8
数据集为CIFAR100，其他均为改变，希望能到解答！

**Comment by VincenDen** [comment]
该框架此前并不支持cifar100，因为这并不是目前小样本领域常用的数据集，所以可能需要您自行适配
