### ISSUE TITLE
在复现文件夹`reproduce/`中缺失部分 method 的 config，详情见图

### ISSUE THREAD

**Issue by Sakiyary** [RL-VIG/LibFewShot#97]
已经查看过所有分支，均缺失以下 method：

<img width="823" alt="f48ccb4ef6b10658a1f8017e669420b7" src="https://github.com/RL-VIG/LibFewShot/assets/60864459/3f41fd9c-0af7-4e2e-87ae-04bee245cf14">

<img width="753" alt="image" src="https://github.com/RL-VIG/LibFewShot/assets/60864459/7b9c9349-8a6d-40c6-8d21-ce556fb46d8c">

**Comment by Sakiyary** [comment]
@stu-yue 在提交记录里看见是您提交这些配置的，请问还有缺失的配置吗？

**Comment by stu-yue** [comment]
你好，Proto在仓库里是有的吧，其他的我fork时好像也没有

**Comment by Sakiyary** [comment]
> 你好，Proto在仓库里是有的吧，其他的我fork时好像也没有

确实，我多圈了 Proto，圈错了这个。那么请问其他 method 的 config 能在哪里获得呢？

**Comment by stu-yue** [comment]
抱歉这个我也不太清楚了，可能得问下之前负责这部分算法的同学？

**Comment by VincenDen** [comment]
https://drive.google.com/drive/u/1/folders/16DWKKqjzALoq4qb8LZQ6oELD9SGlYWe_   可以在该链接找到相关配置文件
